/**
 * All institutional content is sourced from berkshirehathaway.com so the redesign
 * carries the same information as the original site.
 */

export const BASE = "https://www.berkshirehathaway.com";

export type NavItem = { label: string; href: string };

export const NAV: NavItem[] = [
  { label: "Company", href: "#company" },
  { label: "Reports", href: "#reports" },
  { label: "Letters", href: "#letters" },
  { label: "Operations", href: "#operations" },
  { label: "Newsroom", href: "#newsroom" },
  { label: "Investors", href: "#investors" },
];

export const STATS = [
  { value: "1839", label: "Textile roots in New England" },
  { value: "1965", label: "Buffett assumes control" },
  { value: "60+", label: "Wholly owned operating businesses" },
  { value: "26", label: "People at the corporate office" },
];

export type Report = {
  title: string;
  meta: string;
  description: string;
  href: string;
  image?: string;
  featured?: boolean;
};

export const REPORTS: Report[] = [
  {
    title: "2025 Annual Report",
    meta: "Annual · Released February 2026",
    description:
      "The complete annual report to shareholders, including audited financial statements and the chairman's letter.",
    href: `${BASE}/reports.html`,
    image: "/images/report-cover.jpg",
    featured: true,
  },
  {
    title: "First Quarter 2026",
    meta: "Interim · May 2, 2026",
    description: "Quarterly earnings release and Form 10-Q for the period ended March 31, 2026.",
    href: `${BASE}/reports.html`,
  },
  {
    title: "Fourth Quarter 2025",
    meta: "Interim · February 28, 2026",
    description: "Year-end earnings release with segment results and share repurchase detail.",
    href: `${BASE}/reports.html`,
  },
  {
    title: "Report Archive",
    meta: "1995 — 2026",
    description: "Every annual and interim report, quarter by quarter, in one table.",
    href: `${BASE}/reports.html`,
  },
  {
    title: "SEC Filings",
    meta: "EDGAR full-text",
    description: "10-K, 10-Q, 8-K, proxy statements and ownership filings on the SEC's EDGAR system.",
    href: "https://www.sec.gov/cgi-bin/browse-edgar?company=berkshire+hathaway&match=&CIK=&filenum=&State=&Country=&SIC=&owner=exclude&Find=Find+Companies&action=getcompany",
  },
];

export type Letter = {
  title: string;
  range: string;
  description: string;
  href: string;
  updated: string;
};

export const LETTERS: Letter[] = [
  {
    title: "Warren Buffett's Letters to Shareholders",
    range: "1977 — 2024",
    description:
      "Forty-eight consecutive years of annual letters — the primary record of how Berkshire thinks about business, capital and ownership.",
    href: `${BASE}/letters/letters.html`,
    updated: "Updated February 22, 2025",
  },
  {
    title: "Greg Abel's Letters to Shareholders",
    range: "2025 —",
    description:
      "Letters from Berkshire's Chief Executive Officer on operations, capital allocation and the culture the company intends to keep.",
    href: `${BASE}/letters/gealetters.html`,
    updated: "Updated February 28, 2026",
  },
  {
    title: "Special Letters from Warren & Charlie",
    range: "Past, present and future",
    description:
      "Written for Berkshire's fiftieth anniversary: how the partnership worked, what it produced, and what should follow.",
    href: `${BASE}/SpecialLetters/WEBCTMLtr.html`,
    updated: "Anniversary edition",
  },
  {
    title: "Charlie Munger's Letters to Wesco Shareholders",
    range: "Wesco Financial",
    description:
      "The Wesco archive — Munger's own annual accounting of the businesses he oversaw before the 2011 merger.",
    href: `${BASE}/wesco/WescoHome.html`,
    updated: "Historical archive",
  },
];

export type Company = { name: string; href: string };

export type Sector = {
  id: string;
  name: string;
  blurb: string;
  image: string;
  imageAlt: string;
  companies: Company[];
};

export const SECTORS: Sector[] = [
  {
    id: "insurance",
    name: "Insurance & Reinsurance",
    blurb:
      "Underwriting discipline first, volume second. The float generated by these businesses funds much of what Berkshire owns.",
    image: "/images/insurance.jpg",
    imageAlt: "Exterior of a GEICO insurance office with the company sign on a brick facade",
    companies: [
      { name: "GEICO Auto Insurance", href: "https://www.geico.com/" },
      { name: "General Re", href: "https://www.genre.com/" },
      { name: "National Indemnity Company", href: "https://www.nationalindemnity.com/" },
      { name: "Berkshire Hathaway Specialty Insurance", href: "https://bhspecialty.com/" },
      { name: "Berkshire Hathaway GUARD Insurance", href: "https://www.guard.com/" },
      { name: "Berkshire Hathaway Homestate Companies", href: "https://www.bhhc.com/" },
      { name: "Berkshire Hathaway Direct (THREE)", href: "https://threeinsurance.com/" },
      { name: "biBERK Business Insurance", href: "https://www.biberk.com/" },
      { name: "MedPro Group", href: "https://www.medpro.com/" },
      { name: "MLMIC Insurance Company", href: "https://www.mlmic.com/" },
      { name: "United States Liability Insurance", href: "https://www.usli.com/" },
      { name: "Central States Indemnity", href: "https://www.csi-omaha.com/" },
      { name: "Alleghany Corporation", href: "https://www.alleghany.com/about-alleghany/default.aspx" },
      { name: "Gateway Underwriters Agency", href: "https://www.gua-stl.com/" },
      { name: "BoatU.S.", href: "https://www.boatus.com/" },
    ],
  },
  {
    id: "railroad",
    name: "Railroad",
    blurb:
      "One of North America's largest freight networks, moving grain, coal, consumer goods and industrial products across 28 states.",
    image: "/images/rail.jpg",
    imageAlt: "A BNSF freight locomotive crossing a trestle bridge through mountain country",
    companies: [{ name: "BNSF Railway", href: "https://www.bnsf.com/" }],
  },
  {
    id: "energy",
    name: "Energy & Utilities",
    blurb:
      "Regulated utilities, transmission and one of the largest renewable generation portfolios owned by any American utility group.",
    image: "/images/energy.jpg",
    imageAlt: "A row of wind turbines on open grassland at sunset",
    companies: [
      { name: "Berkshire Hathaway Energy Company", href: "https://www.berkshirehathawayenergyco.com/" },
      { name: "Berkshire Hathaway Energy investor presentations", href: `${BASE}/bhenergy/bhenergypresentations.html` },
      { name: "LiquidPower Specialty Products (LSPI)", href: "https://www.liquidpower.com/" },
    ],
  },
  {
    id: "manufacturing",
    name: "Manufacturing & Industrial",
    blurb:
      "Aerospace components, chemicals, building products, metalworking, apparel and specialty equipment — businesses that own their niches.",
    image: "/images/manufacturing.jpg",
    imageAlt: "Robotic arms on a modern automated manufacturing line",
    companies: [
      { name: "Precision Castparts Corp.", href: "https://www.precast.com/" },
      { name: "Lubrizol Corporation", href: "https://www.lubrizol.com/" },
      { name: "Marmon Holdings, Inc.", href: "https://www.marmon.com/" },
      { name: "IMC International Metalworking", href: "https://www.imc-companies.com/" },
      { name: "Johns Manville", href: "https://www.jm.com/" },
      { name: "Shaw Industries", href: "https://www.shawinc.com/" },
      { name: "Benjamin Moore & Co.", href: "https://www.benjaminmoore.com/" },
      { name: "Acme Brick Company", href: "https://www.brick.com/" },
      { name: "MiTek Inc.", href: "https://www.mii.com/" },
      { name: "Clayton Homes", href: "https://www.claytonhomes.com/" },
      { name: "Forest River", href: "https://www.forestriverinc.com/" },
      { name: "Duracell", href: "https://www.duracell.com/en-us/" },
      { name: "Fruit of the Loom Companies", href: `${BASE}/subs/fruit.html` },
      { name: "Brooks Running", href: "https://www.brooksrunning.com/" },
      { name: "Justin Brands", href: `${BASE}/subs/justin.html` },
      { name: "H.H. Brown Shoe Group", href: "https://www.hhbrown.com/" },
      { name: "Garan Incorporated", href: "https://www.garanimals.com/" },
      { name: "Fechheimer Brothers Company", href: "https://www.fechheimer.com/" },
      { name: "Scott Fetzer Companies", href: `${BASE}/subs/scotfetz.html` },
      { name: "W&W/AFCO Steel", href: "https://www.wwafcosteel.com/" },
      { name: "CTB Inc.", href: "https://www.ctbinc.com/" },
      { name: "Bell Laboratories", href: "https://www.belllabs.com/" },
      { name: "Larson-Juhl", href: "https://www.larsonjuhl.com/" },
      { name: "Richline Group", href: "https://www.richlinegroup.com/" },
      { name: "Jazwares", href: "https://www.jazwares.com/" },
      { name: "IPS", href: "https://www.ipsdb.com/" },
    ],
  },
  {
    id: "retail",
    name: "Retail & Consumer",
    blurb:
      "Furniture, jewelry, candy, restaurants and direct selling — long-held brands run by the families and managers who built them.",
    image: "/images/retail.jpg",
    imageAlt: "A See's Candies shop front with its black and white striped awning",
    companies: [
      { name: "See's Candies", href: "https://www.sees.com/" },
      { name: "International Dairy Queen, Inc.", href: "https://www.dairyqueen.com/" },
      { name: "Nebraska Furniture Mart (NFM)", href: "https://www.nfm.com/" },
      { name: "Jordan's Furniture", href: "https://www.jordans.com/" },
      { name: "RC Willey Home Furnishings", href: "https://www.rcwilley.com/" },
      { name: "Star Furniture", href: "https://www.starfurniture.com/" },
      { name: "Borsheims Fine Jewelry", href: "https://www.borsheims.com/" },
      { name: "Helzberg Diamonds", href: "https://www.helzberg.com/" },
      { name: "Ben Bridge Jeweler", href: "https://www.benbridge.com/" },
      { name: "Pampered Chef", href: "https://www.pamperedchef.com/" },
      { name: "Oriental Trading Company", href: "https://www.orientaltrading.com/" },
      { name: "Berkshire Hathaway Automotive", href: "https://www.berkshirehathawayautomotive.com/" },
      { name: "Louis — Motorcycle & Leisure", href: "https://www.louis-moto.com/en" },
      { name: "Pilot Travel Centers", href: "https://pilotflyingj.com/" },
    ],
  },
  {
    id: "services",
    name: "Services & Distribution",
    blurb:
      "Distribution, leasing, flight training, aviation, real estate brokerage and media — asset-heavy businesses with durable demand.",
    image: "/images/hq.jpg",
    imageAlt: "Kiewit Plaza in Omaha, Nebraska, where Berkshire Hathaway keeps its corporate office",
    companies: [
      { name: "McLane Company", href: "https://www.mclaneco.com/" },
      { name: "TTI, Inc.", href: "https://www.tti.com/" },
      { name: "NetJets", href: "https://www.netjets.com/" },
      { name: "FlightSafety", href: "https://www.flightsafety.com/" },
      { name: "XTRA Corporation", href: "https://www.xtralease.com/" },
      { name: "CORT Business Services", href: "https://www.cort.com/" },
      { name: "HomeServices of America", href: "https://www.homeservices.com/" },
      { name: "Business Wire", href: "https://www.businesswire.com/" },
      { name: "WPLG Local 10", href: "https://www.local10.com/" },
      { name: "Charter Brokerage", href: "https://charterbrokerage.net/" },
      { name: "Berkshire Hathaway HomeServices", href: "https://www.homeservices.com/" },
    ],
  },
];

export type NewsItem = { date: string; title: string; tag: string };

export const NEWS: NewsItem[] = [
  { date: "July 24, 2026", title: "Berkshire Hathaway completes acquisition of Taylor Morrison", tag: "Acquisition" },
  {
    date: "May 31, 2026",
    title: "Berkshire Hathaway to acquire Taylor Morrison Home Corporation for $8.5 billion",
    tag: "Acquisition",
  },
  { date: "May 2, 2026", title: "First quarter earnings 2026", tag: "Earnings" },
  {
    date: "April 29, 2026",
    title: "Information regarding first quarter earnings release and 2026 annual shareholders meeting",
    tag: "Notice",
  },
  { date: "February 28, 2026", title: "Fourth quarter earnings 2025", tag: "Earnings" },
  { date: "February 12, 2026", title: "Annual report release information", tag: "Notice" },
  { date: "January 2, 2026", title: "Berkshire Hathaway Inc. completes acquisition of OxyChem", tag: "Acquisition" },
];

export type InvestorCard = {
  title: string;
  body: string;
  linkLabel: string;
  href: string;
};

export const INVESTOR_CARDS: InvestorCard[] = [
  {
    title: "Common stock information",
    body: "Class A (BRK.A) and Class B (BRK.B) both trade on the New York Stock Exchange. Class B carries 1/1500 of the economic interest of a Class A share. Berkshire has never split its Class A stock and pays no dividend — earnings are retained and redeployed.",
    linkLabel: "Shareholder information",
    href: `${BASE}/brkshareholderinfo/brkshareholderinfo.html`,
  },
  {
    title: "Corporate governance",
    body: "Board committees, charters, the code of business conduct and ethics, director independence standards and the governance guidelines that keep the company decentralised but accountable.",
    linkLabel: "Governance documents",
    href: `${BASE}/govern/govern.html`,
  },
  {
    title: "Annual meeting",
    body: "The annual shareholders meeting is held in Omaha, Nebraska. Meeting materials, credentials, shareholder shopping day and visitor guidance are published ahead of each meeting.",
    linkLabel: "Meeting information",
    href: `${BASE}/sharehold.html`,
  },
  {
    title: "Sustainability",
    body: "Berkshire's subsidiaries report on their own environmental and social programmes. The corporate overview explains how oversight works across a decentralised group.",
    linkLabel: "Sustainability overview",
    href: `${BASE}/sustainability/sustainabilityintro.html`,
  },
];

export const FOOTER_COLUMNS: { heading: string; links: NavItem[] }[] = [
  {
    heading: "Financials",
    links: [
      { label: "Annual & interim reports", href: `${BASE}/reports.html` },
      { label: "SEC filings (EDGAR)", href: "https://www.sec.gov/cgi-bin/browse-edgar?company=berkshire+hathaway&match=&CIK=&filenum=&State=&Country=&SIC=&owner=exclude&Find=Find+Companies&action=getcompany" },
      { label: "Common stock information", href: `${BASE}/brkshareholderinfo/brkshareholderinfo.html` },
      { label: "BH Energy investor presentations", href: `${BASE}/bhenergy/bhenergypresentations.html` },
    ],
  },
  {
    heading: "Shareholder letters",
    links: [
      { label: "Warren Buffett's letters", href: `${BASE}/letters/letters.html` },
      { label: "Greg Abel's letters", href: `${BASE}/letters/gealetters.html` },
      { label: "Special letters", href: `${BASE}/SpecialLetters/WEBCTMLtr.html` },
      { label: "Wesco letters (Charlie Munger)", href: `${BASE}/wesco/WescoHome.html` },
    ],
  },
  {
    heading: "Company",
    links: [
      { label: "Operating companies", href: `${BASE}/subs/sublinks.html` },
      { label: "Corporate governance", href: `${BASE}/govern/govern.html` },
      { label: "Sustainability", href: `${BASE}/sustainability/sustainabilityintro.html` },
      { label: "Annual meeting", href: `${BASE}/sharehold.html` },
    ],
  },
  {
    heading: "Notices",
    links: [
      { label: "A message from Warren E. Buffett", href: `${BASE}/message.html` },
      { label: "Fraudulent endorsement claims", href: `${BASE}/webfraud.pdf` },
      { label: "News releases", href: `${BASE}/news/2026news.html` },
      { label: "Legal disclaimer", href: `${BASE}/disclaimer.html` },
    ],
  },
];
